name: Agent Evaluation

on:
  push:
    branches:
        - feature/test-ci-eval
  pull_request:
  workflow_dispatch:


jobs:
  evaluate:
    runs-on: ubuntu-latest

    env:
      AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
      AZURE_OPENAI_SUBSCRIPTION: ${{ secrets.AZURE_OPENAI_SUBSCRIPTION }}
      AZURE_OPENAI_DEPLOYMENT_NAME: ${{ secrets.AZURE_OPENAI_DEPLOYMENT_NAME }}
      AZURE_SEARCH_ENDPOINT: ${{ secrets.AZURE_SEARCH_ENDPOINT }}
      AZURE_SEARCH_API_KEY: ${{ secrets.AZURE_SEARCH_API_KEY }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_EMBED_MODEL_NAME: ${{ secrets.AZURE_EMBED_MODEL_NAME }}
      AZURE_OPENAI_API_VERSION: ${{ secrets.AZURE_OPENAI_API_VERSION }}
      APPLICATIONINSIGHTS_CONNECTION_STRING: ${{ secrets.APPLICATIONINSIGHTS_CONNECTION_STRING }}
      AZURE_SEARCH_INDEX: ${{ secrets.AZURE_SEARCH_INDEX }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Run automated evaluation
        env:
              EXECUTION_MODE: azure
        run: |
          python -m evaluation.run_eval

      - name: Upload evaluation artifacts
        uses: actions/upload-artifact@v4
        with:
          name: agent-evaluation
          path: |
            evaluation/eval_report.json
            evaluation/eval_report.md
