name: CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push image
        run: |
          az acr login --name creditaiacr
          docker build -t creditaiacr.azurecr.io/credit-ai-service:latest .
          docker push creditaiacr.azurecr.io/credit-ai-service:latest

      - name: Set ACR Admin Credentials 
        id: acr_credentials
        run: |
          ACR_USER=$(az acr credential show -n creditaiacr --query 'username' -o tsv)
          ACR_PASS=$(az acr credential show -n creditaiacr --query 'passwords[0].value' -o tsv)
          az containerapp registry set \
            --name credit-ai-app \
            --resource-group credit-ai-rg \
            --server creditaiacr.azurecr.io \
            --username $ACR_USER \
            --password $ACR_PASS
        shell: bash

      - name: Deploy to Azure Container App
        run: |
          az containerapp update \
            --name credit-ai-app \
            --resource-group credit-ai-rg \
            --image creditaiacr.azurecr.io/credit-ai-service:latest